tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f5f3f3',
        'on-secondary-fixed-variant': '#464744',
        'on-secondary-container': '#646561',
        'secondary-fixed': '#e3e3de',
        'tertiary-fixed-dim': '#c9c6c5',
        secondary: '#5e5f5b',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e4e2e2',
        'primary-fixed-dim': '#ffb0ca',
        'inverse-surface': '#303031',
        'on-tertiary': '#ffffff',
        'outline-variant': '#e0bec7',
        surface: '#fbf9f8',
        'on-secondary': '#ffffff',
        tertiary: '#5d5c5b',
        'on-tertiary-fixed-variant': '#474646',
        'primary-fixed': '#ffd9e3',
        'tertiary-container': '#767474',
        'on-secondary-fixed': '#1b1c19',
        'inverse-primary': '#ffb0ca',
        'on-primary': '#ffffff',
        'primary-container': '#da227d',
        background: '#fbf9f8',
        'surface-container': '#efeded',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#3e001f',
        'on-tertiary-container': '#f7feff',
        'on-primary-fixed-variant': '#8d004d',
        'on-background': '#1b1c1c',
        'surface-dim': '#dbdad9',
        'on-surface': '#1b1c1c',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#1c1b1b',
        'surface-container-high': '#e9e8e7',
        'surface-tint': '#b90066',
        'on-primary-container': '#fffbff',
        'on-surface-variant': '#594048',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f2f0f0',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#c7c7c2',
        'on-error': '#ffffff',
        'surface-variant': '#e4e2e2',
        'secondary-container': '#e3e3de',
        primary: '#ff4499',
        'surface-bright': '#fbf9f8',
        outline: '#8d6f78',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        gutter: '24px',
        'stack-lg': '48px',
        'section-gap': '160px',
        'stack-md': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk'],
        'display-lg-mobile': ['Hanken Grotesk'],
        'meta-sm': ['Inter'],
        'display-lg': ['Hanken Grotesk'],
        'body-md': ['Inter'],
        'display-xl': ['Hanken Grotesk'],
        'label-caps': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg': [
          '48px',
          {
            lineHeight: '52px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'display-lg-mobile': [
          '56px',
          {
            lineHeight: '54px',
            letterSpacing: '-0.04em',
            fontWeight: '800',
          },
        ],
        'meta-sm': [
          '12px',
          {
            lineHeight: '18px',
            letterSpacing: '0em',
            fontWeight: '500',
          },
        ],
        'display-lg': [
          '80px',
          {
            lineHeight: '80px',
            letterSpacing: '-0.04em',
            fontWeight: '800',
          },
        ],
        'body-md': [
          '15px',
          {
            lineHeight: '24px',
            letterSpacing: '0em',
            fontWeight: '400',
          },
        ],
        'display-xl': [
          '120px',
          {
            lineHeight: '110px',
            letterSpacing: '-0.04em',
            fontWeight: '800',
          },
        ],
        'label-caps': [
          '12px',
          {
            lineHeight: '16px',
            letterSpacing: '0.1em',
            fontWeight: '700',
          },
        ],
        'headline-md': [
          '32px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.01em',
            fontWeight: '400',
          },
        ],
      },
    },
  },
};
